# Generated by Django 4.0.4 on 2022-07-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_passenger_flight_passenger_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
